### PR TITLE
ENH: Add FluoroSimulator module

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
The "Virtual Cath Lab" module simulates fluoroscopy using a single-plane or bi-plane C-arm.

Motion for each component of the C-arm can be controlled using the module. As the C-arm is moved, the simulated image will be updated in real-time. This image is generated using volume rendering on a CT image using custom transfer functions.

Users can also simulate the addition of contrast agent in the image by filling in segmented regions of the with high intensity values.

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
I don't have the ability to commit directly to SlicerHeart.
This is probably a good place for a discussion as well before this is integrated. In the current publications we refer to the module as the "Virtual Cath Lab" module, instead of the "FluoroSimulator" module.

Do we want to rename the module to "Virtual Cath Lab"?

**Comment by lassoan** [comment]
@Sunderlandkyl I've invited you to this repository with write access so that you can commit.

I like the Virtual Cath Lab module name. It better reflects that the module's scope is not just fluoro image simulation.

**Comment by lassoan** [comment]
Please also add documentation (minimum add a few sentences about it to the main readme file but preferably also add a dedicated page with a few paragraphs of text and fewsl screenshots and reference to the paper.

**Comment by mattjolley** [comment]
@Sunderlandkyl @lassoan 

I will miss the meeting today (pulled clinical), but catch up tomorrow.

We can decide if we are going to wait to release with the manuscript or just put it out there.

From the Cardiac Center and other funding agency perspectives (return on investment) it is important to publish and have something to show for the work we do which is why I try to follow the "publish and release" approach.  This is still far more than most do (publish and release nothing!), but happy to discuss in this case.

I do think it would be good to have this integrated so that it is easier to interface with other projects, but I do want to get credit for all the work we did.  

Thank you.

**Comment by Sunderlandkyl** [comment]
@mattjolley Sorry, I thought that we had decided at the meeting last week to go ahead and make it public.
I'm OK with holding off for now if we want to wait for the publication.

**Comment by mattjolley** [comment]
@Sunderlandkyl 

You are fine.  We just have a bunch of projects that have not been written up and this is one may to help motivate that.  But if we feel the benefits for releasing now outweigh that, we can release.  We can discuss next week.

**Pull request closed without merging**
